/**
 * Created by LDQ on 2016/8/17.
 */

export const SET_PRODUCTID = 'SET_PRODUCTID';
export const GET_PRODUCTID = 'GET_PRODUCTID';
export const SET_STOCKGAMEID = 'SET_STOCKGAMEID';
export const GET_STOCKGAMEID = 'GET_STOCKGAMEID';
export const SET_GUESSTYPE = 'SET_GUESSTYPE';
export const GET_GUESSTYPE = 'GET_GUESSTYPE';
export const SET_PURCHASEGAMEID = 'SET_PURCHASEGAMEID';
export const SET_PRODUCTINFO = 'SET_PRODUCTINFO';

